### ISSUE TITLE
separate TLS private key from [imapd|pop3d].pem

### ISSUE THREAD

**Issue by mumumu** [svarshavchik/courier#10]
As you know, [imapd|pop3d].pem file includes cert file and private key file.

Yes, this rule is not illegal for TLS protocol, but this is a pitfall, because TLS certificate file and private key is usually separated each other. So, I was at pains to incorporate letsencrypt cert file into courier imapd-ssl.

Based on this problem, I propose the following ideas.

- Newly add `TLS_PRIVATE_KEYFILE` setting and existing `TLS_CERTFILE` only includes cert pem file only.
  * I will submit patch!! 
- if `TLS_PRIVATE_KEYFILE` is not acceptable, we should mention about the troublesome rule in `TLS_CERTFILE` comment.
  * https://github.com/svarshavchik/courier-libs/blob/f4569d8153da77b7ad87d98a5818170acea094e6/imap/imapd-ssl.dist.in.git#L201-L230

How do you think?

**Comment by svarshavchik** [comment]
The only real reason for using separate files is to use different file permissions for the private key file, that's the only secret part, while the certificate itself can be publically readable. Furthermore private key can be passphrase-protected, but that's a non-started for daemons that get started at system boot without any interactive environment to protect anyone for the password to decrypt it. There is no real reason to have the the imap, pop3, and the smtp servers publically readable. There's no harm to it but neither there is a reason to have them publicly readable, without divulging the private key.

I am not opposed to having a separate file for the private key, however there needs to be a fallback default, back to a combined file, if the private key file is not specified. Nobody who's already using a combined file setup should have to do anything when updating.

This will also avoid the need to do anything about the mkimapcert, mkesmtpcert, and mkpop3cert helper scripts. They can continue to generate a single file with a self-signed cert.

**Comment by mumumu** [comment]
Thank you for your comments. 
I will try to create a patch by sticking to the following policies.

- Newly add `TLS_PRIVATE_KEY` setting and existing `TLS_CERTFILE` only includes cert pem file only.
- If the `TLS_PRIVATE_KEY` is not specified, fallback to default cert file and private key combined file.
- Do not change mkimapcert, mkesmtpcert, and mkpop3cert helper scripts.

**Comment by mumumu** [comment]
Yes, `TLS_PRIVATE_KEY` is required to support the existing the following features.

- SNI
  * Virtual Host on the same IP Address
- (old) IP Based Virtual Host

**Comment by mumumu** [comment]
@svarshavchik I just finished implementing this feature on OpenSSL. Do I have to implement this feature on GnuTLS? If your answer is yes, I need some more time to implement and test it...

**Comment by svarshavchik** [comment]
Yes, I prefer to keep feature parity between OpenSSL and GnuTLS wherever possible.
