### ISSUE TITLE
Documentation: clarification about maildrop workflow and variables

### ISSUE THREAD

**Issue by mckaygerhard** [svarshavchik/courier#21]
so there's so much variables but no clear workflow, please can you?:

1. can explain clarelly the right workflow and variable usages ?
2. maildrop have significant changes but are not reflected in manpages

some of those changes are the creation of the directories using maildirmake
and the creation of autoreply message files

courierd handle a variable named DEFAULTDELIVERY whrere we can noted a
example about maildrop usage.. BUT in
https://www.courier-mta.org/courier.html said where the maildrop are
installed .. so DEFAULTDELIVERY cannot use that file? are handled
manually for what the courier/maildrop  file then?

https://www.courier-mta.org/maildrop.html saids about rules if some
files are not presents but also courierd and imapd config files  also
defines where maildrop delivery will be..

https://www.courier-mta.org/maildropfilter.html also sais if there's
no file then will deliver to the default mailbox but seems there's no
well documented relation with the variables DEFAULTDELIVERY in
courierd or imapd

**Comment by svarshavchik** [comment]
This was also copied to the mailing list, which has a far wider audience; so closing this as a duplicate.
