### ISSUE TITLE
Issue reported by internet.nl: Client-initiated renegotiation

### ISSUE THREAD

**Issue by andrejpodzimek** [svarshavchik/courier#23]
There doesn't seem to be a way to disable client-initiated renegotiation in courier-mta configs.

![image](https://user-images.githubusercontent.com/947737/75844232-aec84880-5dd5-11ea-9595-416b5d16c1a5.png)

Here's [the link from the screenshot](https://english.ncsc.nl/publications/publications/2019/juni/01/it-security-guidelines-for-transport-layer-security-tls)

**Comment by svarshavchik** [comment]
Feel free to investigate the required new features for both GnuTLS and OpenSSL, and submit a pull request. But, by itself, some issue claimed by some random website on the Internet, that, TMK, nobody else ever heard of, carries very little weight.

**Comment by andrejpodzimek** [comment]
My server with the pull request above (svarshavchik/courier-libs#19) scores "all green" on internet.nl (after I set `TLS_PROTOCOL=TLSv1.2++`).

Just for the record, it sounds rather unfair to call [this page](https://internet.nl/about/) *some random website on the Internet*; I think its reputation has grown way past that over the years.

**Comment by svarshavchik** [comment]
Merged
