### ISSUE TITLE
Cone: tags lost after restarting cone with IMAP connection to outlook.office365.com

### ISSUE THREAD

**Issue by roelvanmeer** [svarshavchik/courier#26]
Hi!

I'm using cone with an IMAP connection to outlook.office365.com. When I tag an email, the line is colored and highlighted.
If I then quit cone and restart it, and reopen the connection to office365, the highlight is gone.

Since I've been using cone for years against a variety of IMAP servers, and this has always worked well, I'm fully convinced that the problem is not with cone but with office365. Still, I would like to see if I can figure out why this breaks.

Could you perhaps give me some hints on where to look? Maybe tags require an IMAP capability that office365 claims to have but doesn't? I've traced the IMAP connection, and I see no commands sent to the server when an email is tagged, which left me fresh out of ideas.

Thank you for your time (and thanks a lot for keeping cone alive in this day and age!)

**Comment by svarshavchik** [comment]
Yes, tags require the IMAP KEYWORDS capability. However if the server doesn't support it the option to tag messages simply won't work at all.

**Comment by roelvanmeer** [comment]
That might be it then. The Office365 IMAP server supports the following flags:

`* FLAGS (\Seen \Answered \Flagged \Deleted \Draft $MDNSent)`

while the Cyrus server I checked has:

`* FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Label1 $Label3 $Label4 $Label5 $Label6 $Label7 $Label8 $Label9 $Label2 $NotJunk $Junk NonJunk $Forwarded)`

So I guess I'm out of luck here. Thanks for your time!
