### ISSUE TITLE
Matching against fields other than DN / emailAddress in TLS_EXTERNAL

### ISSUE THREAD

**Issue by andrejpodzimek** [svarshavchik/courier#29]
This is a humble feature request. (It may be already possible / implemented, but I was unable to find it in the documentation.)

OpenSSL's `ca` man page says: *&hellip;it is good policy just having the e-mail set into the altName extension of the certificate&hellip;* (In other words, `email_in_dn` should be set to `no` in in the CA's configuration.)

Unfortunately, it seems that certificates adhering to this^^^ policy cannot be used for certificate authentication in Courier.

Is it possible to reference a X509v3 Subject Alternative Name (SAN) (which reads `email:user@domain.org` in OpenSSL's output) using `TLS_EXTERNAL`? What would be the syntax?

**Comment by andrejpodzimek** [comment]
And it looks like `TLS_EXTERNAL` is only inspected in `libs/imap/externalauth.c`, but the configuration file comments in `esmtpd-ssl` suggest that it should exist also in SMTP.

**Comment by svarshavchik** [comment]
That code is used in the smtp server too. No, currently there's no syntax for using any other field as the authentication key.

**Comment by svarshavchik** [comment]
If someone gets around to submitting a patch or a PR, I'll review it.
