### ISSUE TITLE
compiling from source

### ISSUE THREAD

**Issue by jacksnodgrass** [svarshavchik/courier#3]
( weird that this is the first issue... doesn't seem right... ) 

Tried on both a Fedora 23 and a Debian 8 system. Think I followed the instructions correctly... 
make sure that utoconf automake libtool gettext sysconftool are all installed... 

git clone https://github.com/svarshavchik/courier.git
cd courier
sh INSTALLME courier https://github.com/svarshavchik/courier-libs.git

configure.ac:16: installing './compile'
configure.ac:11: installing './missing'
/home/jack/courier/courier/afx:
configure.ac:9: error: required file 'config.h.in' not found
Makefile.am: installing '../depcomp'

... what did I miss?

**Comment by svarshavchik** [comment]
The missing step is probably running the autobloat script, as described at the end of the INSTALLME file.
