### ISSUE TITLE
`imapd-ssl` startup script doesn’t have a `restart` option

### ISSUE THREAD

**Issue by andrejpodzimek** [svarshavchik/courier#34]
All of `esmtpd`, `esmtpd-ssl` and `imapd` understand a `restart` option, but [`imapd-ssl`](https://github.com/svarshavchik/courier/blob/master/courier-imap/imapd-ssl.rc.in) doesn’t. Is this intentional for technical reasons or can a `restart` option be added?

**Comment by svarshavchik** [comment]
Just that it was never needed, for any particular reason. I added it.

**Comment by neilromig** [comment]
Shouldn't line 75 of imapd.rc.in be "restart)" ?

**Comment by svarshavchik** [comment]
All-right, fixed up.
