### ISSUE TITLE
Cone 1.5 - interop problem with Office365

### ISSUE THREAD

**Issue by roelvanmeer** [svarshavchik/courier#39]
Not a cone issue, but an interoperability problem. I'm testing cone 1.5 against Microsoft Office365, and it (Microsoft) gives me the error "Command Argument Error. 11". Is there a way to have a debug transcription of the IMAP conversation, so I can find out what's going wrong here? Because the connection is encrypted using strace didn't get me anywhere.

An older version (0.96.2) is currently working btw.

**Comment by roelvanmeer** [comment]
Ah, /debugio is very helpful

**Comment by roelvanmeer** [comment]
[imap-conversation.txt](https://github.com/svarshavchik/courier/files/8326036/imap-conversation.txt)

These are the two debugio transcripts, one from cone 0.96.2 (working) and one with cone 1.5 (not working). Could you perhaps take a quick look and see if there's anything that stands out?

Note that I replaced the backslash r and backslash n with forward slashes, because github didn't want to process the file otherwise.

Thanks a lot! Roel

**Comment by svarshavchik** [comment]
It looks like in 0.96.2 it's providing a password.  Cone 1.5 is sending an empty password, and Office 365 chokes on an empty password.

Wrrite.SSL(4): roel@******** {11}/r/n

That's cone telling Office365 that the password will be sent and it's 11 characters. In the other one:

Write.SSL(4): roel@******** {0}/r/n

That's cone telling Office365 that the password will be sent and it's 0 characters long.

Delete the account and recreate it, making sure to specify a password.

**Comment by roelvanmeer** [comment]
Eh, I feel stupid now. Sorry for wasting your time.
