### ISSUE TITLE
Does maildrop plan to switch to pcre2?

### ISSUE THREAD

**Issue by nlgwcy** [svarshavchik/courier#41]
The upstream maintenance of pcre is about to stop and needs to be switched to pcre2. Does maildrop plan to switch to pcre2?
![image](https://user-images.githubusercontent.com/85690076/167092964-da042e5f-1629-4d75-9fc6-495f5bbcd30d.png)
http://www.pcre.org/

**Comment by svarshavchik** [comment]
The current version of maildrop builds against pcre2.
