### ISSUE TITLE
How to disable "IMAP SERVER ALERT" displayed in Outlook

### ISSUE THREAD

**Issue by mvidalinc** [svarshavchik/courier#42]
Hello,

I'm a mail server administrator for real estate agencies and after having upgrading from Debian 8 to Debian 11, my customers are complaining about an Outlook alert popup, displayed at the bottom right of the screen, on Windows, saying : 

Title : "IMAP SERVER ALERT"
Message : "Votre serveur IMAP souhaite vous alerter à propos de : Your IMAP client does not appear to correctly implement Unicode messages, see https://tools.ietf.org/html/rfc6855.html"

I didn't have this problem before, with Courier on Debian 8. I searched Google but found no solution to that.

It's not possible to disable the "IMAP SERVER ALERT" in Outlook without disable all the Outlook notifications, and some of my customers want the notification when a new message arrives.

How can I disable this alert inside /etc/courier/, on the server side ?

Thank you very much.

PS : sorry if I'm not in the right place.

**Comment by svarshavchik** [comment]
A Unicode-compatible mail client is required to correctly open and read Unicode-formatted mail.

Your clients can try contacting whoever's sending them mail and ask them to stop sending Unicode-formatted E-mail; or perhaps they can try to update their mail client to the one that supports Unicode-formatted E-mail. RFC 6855, the IMAP standard for Unicode, was published in 2013; hopefully by now there's a Unicode-compatible version of Outlook that can be updated to.

I'm unfamiliar with which version of Courier is packaged for Debian 11; the current version automatically limits these alerts to one per session, per message, that's the most that can be done. RFC 6855 instructs mail servers to alert clients if they attempt to open a Unicode-formatted message in a client that did not indicate that it supports the updated IMAP standard, and this is the minimal amount of notifications.

**Comment by mvidalinc** [comment]
Thank you very much for your answer. I just found an option in Outlook to use "Unicode (UTF-8)" for outgoing messages, instead of "Alphabet Occidental (ISO)", as explained here : https://support.streetcontxt.com/hc/en-us/articles/360015329011-Setting-Default-Encoding-In-Outlook

I will see today if it's working.

**Comment by svarshavchik** [comment]
This is something else. There should not be any explicit setting for this. This is something that should be enabled automatically. The mail server indicates that it supports Unicode mail, this indication is a core part of the protocol, and the mail client automatically enables it, without the need for any kind of a setting.

**Comment by mvidalinc** [comment]
I understand. So, maybe a more recent version of Outlook has not this problem.

Thank you.
