### ISSUE TITLE
checking courier-unicode library and version - compiling error

### ISSUE THREAD

**Issue by s-s-s** [svarshavchik/courier#45]
Hi! 
Which option should be set so that the compilation sees the installed package?
Thank's

# uname -a
FreeBSD 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 GENERIC i386

# ./configure
...
checking courier-unicode library and version... configure: error: ERROR: The Courier Unicode Library 2.2.4 header files appear not to be installed.
You may need to upgrade the library or install a separate development
subpackage in addition to the main package.

# pkg info
...
courier-authlib-0.71.5         Meta-port for the courier authentication library
courier-authlib-base-0.71.5    Courier authentication library base
courier-unicode-2.2.4          Courier implementation of Unicode Standard related algorithms
...

**Comment by svarshavchik** [comment]
I am not familiar with FreeBSD's packaging. If FreeBSD's packaging follows common naming convention it would be a separate -devel subpackage, please check with the FreeBSD's packager for more information.
