### ISSUE TITLE
Missing some options in esmtpd-ssl.dist

### ISSUE THREAD

**Issue by ploink** [svarshavchik/courier#46]
I wanted the options ESMTPAUTH and BLACKLISTS in esmtpd-ssl to be different from the esmtpd config file. They were not there by default, so I added them manually. This worked fine until the next update when they disappeared. I suppose the config file is recreated form esmtpd-ssl.dist with every update and any options that are not in the dist disappear.
Can they be added?

My use case:
- I want to disable logins on port 25 to fend off bots trying to guess passwords.
Setting ESMTPAUTH="" in esmtpd file does the trick, but then I want to require logins for ssl port 465 with ESMTPAUTH="PLAIN LOGIN" and AUTH_REQUIRED="1" in esmtp-ssl.
- I do not need blacklists for authenticated ssl users, disabled with BLACKLISTS="".

**Comment by svarshavchik** [comment]
Courier's stock installation script should reset configuration file settings only when they change in the updated version. It's possible that some Linux distribution's installation script does its own thing and replaces the config file each time, nothing much can be done about it.

Still, there is no convenient place to put anything like this right now, so I added a MISC section at the end of esmtpd-ssl.dist that'll defined as an unchangeable configuration section, so going forward it will be safe to put in any custom settings there.

**Comment by ploink** [comment]
Today I upgraded Fedora 35 to 36 and courier to 1.2.0.  I always build/update courier from rpm packages using the included spec file.
This did not reproduce the problem so I am unsure what exactly happened. (Not using the MISC section yet)

Anyway I now implemented your solution.
Thank you!
