### ISSUE TITLE
Missing license information?

### ISSUE THREAD

**Issue by comburent** [svarshavchik/courier#53]
https://github.com/svarshavchik/courier/blob/master/courier/COPYING.GPL says `libs/common/COPYING.GPL` but I can't this directory/file within the repository.

P.S.: Consider using something like [REUSE](https://reuse.software/tutorial/) to convey licensing information in an unambiguous manner instead of a plain COPYING file.

**Comment by svarshavchik** [comment]
This is referring to the courier-libs repository, when it gets packaged together with courier into a single source package.
